# Generated by Django 4.1 on 2022-08-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name of News')),
                ('content', models.TextField(verbose_name='Main News')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('draft', models.BooleanField(default=True, verbose_name='Should be post?')),
                ('image', models.ImageField(null=True, upload_to='news_image', verbose_name='Add image')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('clicked', models.IntegerField(default=0, editable=False)),
                ('categories', models.ManyToManyField(null=True, related_name='category_blog', to='blog.category')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'More News',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooment_news', to='blog.news', verbose_name='News')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
