# Generated by Django 4.1 on 2022-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_image_alter_comment_created_date_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='Comment_User', verbose_name='Image'),
        ),
    ]
