# Generated by Django 4.1 on 2022-08-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_az',
            field=models.CharField(max_length=25, null=True, verbose_name='Category title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Category title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_tr',
            field=models.CharField(max_length=25, null=True, verbose_name='Category title'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_az',
            field=models.TextField(null=True, verbose_name='Main News'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Main News'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='Main News'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Name of News'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name of News'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name of News'),
        ),
    ]
